#!/usr/bin/env Rscript

args = commandArgs(trailingOnly=TRUE)

if (length(args) < 2) {
  stop("First provide the genome path, second the Dfam database", call.=FALSE)
} else if (length(args) > 2) {
 stop("More than two arguments were created", call.=FALSE)
}

#Inputs
genome=args[1]
Dfam_db=args[2]
mutation_rate= 9.1 * 1E-9
cores=48
similar = 80                                                                                                                                                                                                                                                                                                         
mintsd = 4                                                                                                                                                                                                                                                                                                            
maxtsd = 18 
overlaps = "best"
tRNAs =  paste0(system.file("tRNAs/", package = "LTRpred"),"plants-tRNA_cat.fa")
hmms = paste0(system.file("HMMs/", package = "LTRpred"), "hmm_*")
cluster     = TRUE
clust.sim   = 0.8

#Main
LTRpred::LTRpred(
genome.file = genome,
model = "K80",                                                                                                                                                                                                                                                                                                          
mutation_rate = mutation_rate,                                                                                                                                                                                                                                                                                            
index.file.harvest = NULL,                                                                                                                                                                                                                                                                                              
index.file.digest = NULL,                                                                                                                                                                                                                                                                                               
LTRdigest.gff = NULL,                                                                                                                                                                                                                                                                                                   
tabout.file = NULL,                                                                                                                                                                                                                                                                                                     
LTRharvest.folder = NULL,                                                                                                                                                                                                                                                                                               
LTRpred.folder = NULL,                                                                                                                                                                                                                                                                                                  
orf.file = NULL,                                                                                                                                                                                                                                                                                                        
annotate = "Dfam",                                                                                                                                                                                                                                                                                                        
Dfam.db = Dfam_db,                                                                                                                                                                                                                                                                                       
dfam.eval = 0.001,                                                                                                                                                                                                                                                                                                      
dfam.file = NULL,                                                                                                                                                                                                                                                                                                       
cluster = TRUE,                                                                                                                                                                                                                                                                                                        
clust.sim = 0.9,                                                                                                                                                                                                                                                                                                        
clust.file = NULL,                                                                                                                                                                                                                                                                                                      
copy.number.est = TRUE,                                                                                                                                                                                                                                                                                                 
fix.chr.name = TRUE,                                                                                                                                                                                                                                                                                                    
cn.eval = 1e-10,                                                                                                                                                                                                                                                                                                        
range = c(0, 0),                                                                                                                                                                                                                                                                                                        
seed = 30,                                                                                                                                                                                                                                                                                                              
minlenltr = 100,                                                                                                                                                                                                                                                                                                        
maxlenltr = 3500,                                                                                                                                                                                                                                                                                                       
mindistltr = 4000,                                                                                                                                                                                                                                                                                                      
maxdistltr = 25000,                                                                                                                                                                                                                                                                                                     
similar = similar,                                                                                                                                                                                                                                                                                                           
mintsd = mintsd,                                                                                                                                                                                                                                                                                                             
maxtsd = maxtsd,                                                                                                                                                                                                                                                                                                            
vic = 60,                                                                                                                                                                                                                                                                                                               
overlaps = overlaps,                                                                                                                                                                                                                                                                                                        
xdrop = 5,                                                                                                                                                                                                                                                                                                              
mat = 2,                                                                                                                                                                                                                                                                                                                
mis = -2,                                                                                                                                                                                                                                                                                                               
ins = -3,                                                                                                                                                                                                                                                                                                               
del = -3,                                                                                                                                                                                                                                                                                                               
motif = NULL,                                                                                                                                                                                                                                                                                                           
motifmis = 0,                                                                                                                                                                                                                                                                                                           
aaout = "yes",                                                                                                                                                                                                                                                                                                          
aliout = "yes",                                                                                                                                                                                                                                                                                                         
pptlen = c(8, 30),                                                                                                                                                                                                                                                                                                      
uboxlen = c(3, 30),                                                                                                                                                                                                                                                                                                     
pptradius = 30,                                                                                                                                                                                                                                                                                                         
trnas = tRNAs,                                                                                                                                                                                                                                                                                                           
pbsalilen = c(11, 30),                                                                                                                                                                                                                                                                                                  
pbsoffset = c(0,5),                                                                                                                                                                                                                                                                                                     
pbstrnaoffset = c(0, 5),                                                                                                                                                                                                                                                                                                
pbsmaxedist = 1,                                                                                                                                                                                                                                                                                                        
pbsradius = 30,                                                                                                                                                                                                                                                                                                         
hmms = hmms,                                                                                                                                                                                                                                                                                                            
pdomevalcutoff = 1e-05,                                                                                                                                                                                                                                                                                                 
pbsmatchscore = 5,                                                                                                                                                                                                                                                                                                      
pbsmismatchscore = -10,                                                                                                                                                                                                                                                                                                 
pbsinsertionscore = -20,                                                                                                                                                                                                                                                                                                
pbsdeletionscore = -20,                                                                                                                                                                                                                                                                                                 
pfam.ids = NULL,                                                                                                                                                                                                                                                                                                        
cores = cores,                                                                                                                                                                                                                                                                                                              
dfam.cores = cores,                                                                                                                                                                                                                                                                                                      
hmm.cores = cores,                                                                                                                                                                                                                                                                                                       
orf.style = 7,                                                                                                                                                                                                                                                                                                          
min.codons = 200,                                                                                                                                                                                                                                                                                                       
trans.seqs = FALSE,                                                                                                                                                                                                                                                                                                     
output.path = NULL,                                                                                                                                                                                                                                                                                                     
quality.filter = TRUE,                                                                                                                                                                                                                                                                                                  
n.orfs = 0,                                                                                                                                                                                                                                                                                                             
verbose = TRUE                                                                                                                                                                                                                                                                                                          
)        
